/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as PreviewWebsiteRouteImport } from './routes/preview-website'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoReadyRouteImport } from './routes/demo-ready'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as RisksIndexRouteImport } from './routes/risks.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as GapsIndexRouteImport } from './routes/gaps.index'
import { Route as FrameworksIndexRouteImport } from './routes/frameworks.index'
import { Route as ControlsIndexRouteImport } from './routes/controls.index'
import { Route as VendorsReviewsRouteImport } from './routes/vendors.reviews'
import { Route as VendorsDiscoveryRouteImport } from './routes/vendors.discovery'
import { Route as VendorsAllRouteImport } from './routes/vendors.all'
import { Route as VendorsIdRouteImport } from './routes/vendors.$id'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as RisksIdRouteImport } from './routes/risks.$id'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as IntegrationsGoogleWorkspaceRouteImport } from './routes/integrations.google-workspace'
import { Route as IntegrationsIdRouteImport } from './routes/integrations.$id'
import { Route as GapsIdRouteImport } from './routes/gaps.$id'
import { Route as FrameworksIdRouteImport } from './routes/frameworks.$id'
import { Route as ControlsIdRouteImport } from './routes/controls.$id'
import { Route as AssessmentsIso27001RouteImport } from './routes/assessments.iso-27001'
import { Route as AssessmentsIso27001DomainIdRouteImport } from './routes/assessments.iso-27001.$domainId'
import { Route as ApiIntegrationsGoogleWorkspaceUsersRouteImport } from './routes/api.integrations.google-workspace.users'
import { Route as ApiIntegrationsGoogleWorkspaceSyncRouteImport } from './routes/api.integrations.google-workspace.sync'
import { Route as ApiIntegrationsGoogleWorkspaceStatusRouteImport } from './routes/api.integrations.google-workspace.status'
import { Route as ApiIntegrationsGoogleWorkspaceGroupsRouteImport } from './routes/api.integrations.google-workspace.groups'
import { Route as ApiIntegrationsGoogleWorkspaceFindingsRouteImport } from './routes/api.integrations.google-workspace.findings'
import { Route as ApiIntegrationsGoogleWorkspaceDisconnectRouteImport } from './routes/api.integrations.google-workspace.disconnect'
import { Route as ApiIntegrationsGoogleWorkspaceConnectUrlRouteImport } from './routes/api.integrations.google-workspace.connect-url'
import { Route as ApiIntegrationsGoogleWorkspaceOauthCallbackRouteImport } from './routes/api.integrations.google-workspace.oauth.callback'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewWebsiteRoute = PreviewWebsiteRouteImport.update({
  id: '/preview-website',
  path: '/preview-website',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoReadyRoute = DemoReadyRouteImport.update({
  id: '/demo-ready',
  path: '/demo-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksIndexRoute = RisksIndexRouteImport.update({
  id: '/risks/',
  path: '/risks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsIndexRoute = GapsIndexRouteImport.update({
  id: '/gaps/',
  path: '/gaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksIndexRoute = FrameworksIndexRouteImport.update({
  id: '/frameworks/',
  path: '/frameworks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsIndexRoute = ControlsIndexRouteImport.update({
  id: '/controls/',
  path: '/controls/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsReviewsRoute = VendorsReviewsRouteImport.update({
  id: '/vendors/reviews',
  path: '/vendors/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsDiscoveryRoute = VendorsDiscoveryRouteImport.update({
  id: '/vendors/discovery',
  path: '/vendors/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsAllRoute = VendorsAllRouteImport.update({
  id: '/vendors/all',
  path: '/vendors/all',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksIdRoute = RisksIdRouteImport.update({
  id: '/risks/$id',
  path: '/risks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsGoogleWorkspaceRoute =
  IntegrationsGoogleWorkspaceRouteImport.update({
    id: '/integrations/google-workspace',
    path: '/integrations/google-workspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsIdRoute = IntegrationsIdRouteImport.update({
  id: '/integrations/$id',
  path: '/integrations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsIdRoute = GapsIdRouteImport.update({
  id: '/gaps/$id',
  path: '/gaps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksIdRoute = FrameworksIdRouteImport.update({
  id: '/frameworks/$id',
  path: '/frameworks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsIdRoute = ControlsIdRouteImport.update({
  id: '/controls/$id',
  path: '/controls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIso27001Route = AssessmentsIso27001RouteImport.update({
  id: '/assessments/iso-27001',
  path: '/assessments/iso-27001',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIso27001DomainIdRoute =
  AssessmentsIso27001DomainIdRouteImport.update({
    id: '/$domainId',
    path: '/$domainId',
    getParentRoute: () => AssessmentsIso27001Route,
  } as any)
const ApiIntegrationsGoogleWorkspaceUsersRoute =
  ApiIntegrationsGoogleWorkspaceUsersRouteImport.update({
    id: '/api/integrations/google-workspace/users',
    path: '/api/integrations/google-workspace/users',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceSyncRoute =
  ApiIntegrationsGoogleWorkspaceSyncRouteImport.update({
    id: '/api/integrations/google-workspace/sync',
    path: '/api/integrations/google-workspace/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceStatusRoute =
  ApiIntegrationsGoogleWorkspaceStatusRouteImport.update({
    id: '/api/integrations/google-workspace/status',
    path: '/api/integrations/google-workspace/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceGroupsRoute =
  ApiIntegrationsGoogleWorkspaceGroupsRouteImport.update({
    id: '/api/integrations/google-workspace/groups',
    path: '/api/integrations/google-workspace/groups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceFindingsRoute =
  ApiIntegrationsGoogleWorkspaceFindingsRouteImport.update({
    id: '/api/integrations/google-workspace/findings',
    path: '/api/integrations/google-workspace/findings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceDisconnectRoute =
  ApiIntegrationsGoogleWorkspaceDisconnectRouteImport.update({
    id: '/api/integrations/google-workspace/disconnect',
    path: '/api/integrations/google-workspace/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceConnectUrlRoute =
  ApiIntegrationsGoogleWorkspaceConnectUrlRouteImport.update({
    id: '/api/integrations/google-workspace/connect-url',
    path: '/api/integrations/google-workspace/connect-url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleWorkspaceOauthCallbackRoute =
  ApiIntegrationsGoogleWorkspaceOauthCallbackRouteImport.update({
    id: '/api/integrations/google-workspace/oauth/callback',
    path: '/api/integrations/google-workspace/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-ready': typeof DemoReadyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/preview-website': typeof PreviewWebsiteRoute
  '/request-demo': typeof RequestDemoRoute
  '/settings': typeof SettingsRoute
  '/tests': typeof TestsRoute
  '/assessments/iso-27001': typeof AssessmentsIso27001RouteWithChildren
  '/controls/$id': typeof ControlsIdRoute
  '/frameworks/$id': typeof FrameworksIdRoute
  '/gaps/$id': typeof GapsIdRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/integrations/google-workspace': typeof IntegrationsGoogleWorkspaceRoute
  '/reports/$id': typeof ReportsIdRoute
  '/risks/$id': typeof RisksIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/all': typeof VendorsAllRoute
  '/vendors/discovery': typeof VendorsDiscoveryRoute
  '/vendors/reviews': typeof VendorsReviewsRoute
  '/controls/': typeof ControlsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
  '/gaps/': typeof GapsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/risks/': typeof RisksIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/assessments/iso-27001/$domainId': typeof AssessmentsIso27001DomainIdRoute
  '/api/integrations/google-workspace/connect-url': typeof ApiIntegrationsGoogleWorkspaceConnectUrlRoute
  '/api/integrations/google-workspace/disconnect': typeof ApiIntegrationsGoogleWorkspaceDisconnectRoute
  '/api/integrations/google-workspace/findings': typeof ApiIntegrationsGoogleWorkspaceFindingsRoute
  '/api/integrations/google-workspace/groups': typeof ApiIntegrationsGoogleWorkspaceGroupsRoute
  '/api/integrations/google-workspace/status': typeof ApiIntegrationsGoogleWorkspaceStatusRoute
  '/api/integrations/google-workspace/sync': typeof ApiIntegrationsGoogleWorkspaceSyncRoute
  '/api/integrations/google-workspace/users': typeof ApiIntegrationsGoogleWorkspaceUsersRoute
  '/api/integrations/google-workspace/oauth/callback': typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-ready': typeof DemoReadyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/preview-website': typeof PreviewWebsiteRoute
  '/request-demo': typeof RequestDemoRoute
  '/settings': typeof SettingsRoute
  '/tests': typeof TestsRoute
  '/assessments/iso-27001': typeof AssessmentsIso27001RouteWithChildren
  '/controls/$id': typeof ControlsIdRoute
  '/frameworks/$id': typeof FrameworksIdRoute
  '/gaps/$id': typeof GapsIdRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/integrations/google-workspace': typeof IntegrationsGoogleWorkspaceRoute
  '/reports/$id': typeof ReportsIdRoute
  '/risks/$id': typeof RisksIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/all': typeof VendorsAllRoute
  '/vendors/discovery': typeof VendorsDiscoveryRoute
  '/vendors/reviews': typeof VendorsReviewsRoute
  '/controls': typeof ControlsIndexRoute
  '/frameworks': typeof FrameworksIndexRoute
  '/gaps': typeof GapsIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/risks': typeof RisksIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/assessments/iso-27001/$domainId': typeof AssessmentsIso27001DomainIdRoute
  '/api/integrations/google-workspace/connect-url': typeof ApiIntegrationsGoogleWorkspaceConnectUrlRoute
  '/api/integrations/google-workspace/disconnect': typeof ApiIntegrationsGoogleWorkspaceDisconnectRoute
  '/api/integrations/google-workspace/findings': typeof ApiIntegrationsGoogleWorkspaceFindingsRoute
  '/api/integrations/google-workspace/groups': typeof ApiIntegrationsGoogleWorkspaceGroupsRoute
  '/api/integrations/google-workspace/status': typeof ApiIntegrationsGoogleWorkspaceStatusRoute
  '/api/integrations/google-workspace/sync': typeof ApiIntegrationsGoogleWorkspaceSyncRoute
  '/api/integrations/google-workspace/users': typeof ApiIntegrationsGoogleWorkspaceUsersRoute
  '/api/integrations/google-workspace/oauth/callback': typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-ready': typeof DemoReadyRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/policies': typeof PoliciesRoute
  '/preview-website': typeof PreviewWebsiteRoute
  '/request-demo': typeof RequestDemoRoute
  '/settings': typeof SettingsRoute
  '/tests': typeof TestsRoute
  '/assessments/iso-27001': typeof AssessmentsIso27001RouteWithChildren
  '/controls/$id': typeof ControlsIdRoute
  '/frameworks/$id': typeof FrameworksIdRoute
  '/gaps/$id': typeof GapsIdRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/integrations/google-workspace': typeof IntegrationsGoogleWorkspaceRoute
  '/reports/$id': typeof ReportsIdRoute
  '/risks/$id': typeof RisksIdRoute
  '/tasks/$id': typeof TasksIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/vendors/all': typeof VendorsAllRoute
  '/vendors/discovery': typeof VendorsDiscoveryRoute
  '/vendors/reviews': typeof VendorsReviewsRoute
  '/controls/': typeof ControlsIndexRoute
  '/frameworks/': typeof FrameworksIndexRoute
  '/gaps/': typeof GapsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/risks/': typeof RisksIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/assessments/iso-27001/$domainId': typeof AssessmentsIso27001DomainIdRoute
  '/api/integrations/google-workspace/connect-url': typeof ApiIntegrationsGoogleWorkspaceConnectUrlRoute
  '/api/integrations/google-workspace/disconnect': typeof ApiIntegrationsGoogleWorkspaceDisconnectRoute
  '/api/integrations/google-workspace/findings': typeof ApiIntegrationsGoogleWorkspaceFindingsRoute
  '/api/integrations/google-workspace/groups': typeof ApiIntegrationsGoogleWorkspaceGroupsRoute
  '/api/integrations/google-workspace/status': typeof ApiIntegrationsGoogleWorkspaceStatusRoute
  '/api/integrations/google-workspace/sync': typeof ApiIntegrationsGoogleWorkspaceSyncRoute
  '/api/integrations/google-workspace/users': typeof ApiIntegrationsGoogleWorkspaceUsersRoute
  '/api/integrations/google-workspace/oauth/callback': typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo-ready'
    | '/login'
    | '/onboarding'
    | '/overview'
    | '/policies'
    | '/preview-website'
    | '/request-demo'
    | '/settings'
    | '/tests'
    | '/assessments/iso-27001'
    | '/controls/$id'
    | '/frameworks/$id'
    | '/gaps/$id'
    | '/integrations/$id'
    | '/integrations/google-workspace'
    | '/reports/$id'
    | '/risks/$id'
    | '/tasks/$id'
    | '/vendors/$id'
    | '/vendors/all'
    | '/vendors/discovery'
    | '/vendors/reviews'
    | '/controls/'
    | '/frameworks/'
    | '/gaps/'
    | '/integrations/'
    | '/reports/'
    | '/risks/'
    | '/tasks/'
    | '/vendors/'
    | '/assessments/iso-27001/$domainId'
    | '/api/integrations/google-workspace/connect-url'
    | '/api/integrations/google-workspace/disconnect'
    | '/api/integrations/google-workspace/findings'
    | '/api/integrations/google-workspace/groups'
    | '/api/integrations/google-workspace/status'
    | '/api/integrations/google-workspace/sync'
    | '/api/integrations/google-workspace/users'
    | '/api/integrations/google-workspace/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo-ready'
    | '/login'
    | '/onboarding'
    | '/overview'
    | '/policies'
    | '/preview-website'
    | '/request-demo'
    | '/settings'
    | '/tests'
    | '/assessments/iso-27001'
    | '/controls/$id'
    | '/frameworks/$id'
    | '/gaps/$id'
    | '/integrations/$id'
    | '/integrations/google-workspace'
    | '/reports/$id'
    | '/risks/$id'
    | '/tasks/$id'
    | '/vendors/$id'
    | '/vendors/all'
    | '/vendors/discovery'
    | '/vendors/reviews'
    | '/controls'
    | '/frameworks'
    | '/gaps'
    | '/integrations'
    | '/reports'
    | '/risks'
    | '/tasks'
    | '/vendors'
    | '/assessments/iso-27001/$domainId'
    | '/api/integrations/google-workspace/connect-url'
    | '/api/integrations/google-workspace/disconnect'
    | '/api/integrations/google-workspace/findings'
    | '/api/integrations/google-workspace/groups'
    | '/api/integrations/google-workspace/status'
    | '/api/integrations/google-workspace/sync'
    | '/api/integrations/google-workspace/users'
    | '/api/integrations/google-workspace/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/demo-ready'
    | '/login'
    | '/onboarding'
    | '/overview'
    | '/policies'
    | '/preview-website'
    | '/request-demo'
    | '/settings'
    | '/tests'
    | '/assessments/iso-27001'
    | '/controls/$id'
    | '/frameworks/$id'
    | '/gaps/$id'
    | '/integrations/$id'
    | '/integrations/google-workspace'
    | '/reports/$id'
    | '/risks/$id'
    | '/tasks/$id'
    | '/vendors/$id'
    | '/vendors/all'
    | '/vendors/discovery'
    | '/vendors/reviews'
    | '/controls/'
    | '/frameworks/'
    | '/gaps/'
    | '/integrations/'
    | '/reports/'
    | '/risks/'
    | '/tasks/'
    | '/vendors/'
    | '/assessments/iso-27001/$domainId'
    | '/api/integrations/google-workspace/connect-url'
    | '/api/integrations/google-workspace/disconnect'
    | '/api/integrations/google-workspace/findings'
    | '/api/integrations/google-workspace/groups'
    | '/api/integrations/google-workspace/status'
    | '/api/integrations/google-workspace/sync'
    | '/api/integrations/google-workspace/users'
    | '/api/integrations/google-workspace/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoReadyRoute: typeof DemoReadyRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OverviewRoute: typeof OverviewRoute
  PoliciesRoute: typeof PoliciesRoute
  PreviewWebsiteRoute: typeof PreviewWebsiteRoute
  RequestDemoRoute: typeof RequestDemoRoute
  SettingsRoute: typeof SettingsRoute
  TestsRoute: typeof TestsRoute
  AssessmentsIso27001Route: typeof AssessmentsIso27001RouteWithChildren
  ControlsIdRoute: typeof ControlsIdRoute
  FrameworksIdRoute: typeof FrameworksIdRoute
  GapsIdRoute: typeof GapsIdRoute
  IntegrationsIdRoute: typeof IntegrationsIdRoute
  IntegrationsGoogleWorkspaceRoute: typeof IntegrationsGoogleWorkspaceRoute
  ReportsIdRoute: typeof ReportsIdRoute
  RisksIdRoute: typeof RisksIdRoute
  TasksIdRoute: typeof TasksIdRoute
  VendorsIdRoute: typeof VendorsIdRoute
  VendorsAllRoute: typeof VendorsAllRoute
  VendorsDiscoveryRoute: typeof VendorsDiscoveryRoute
  VendorsReviewsRoute: typeof VendorsReviewsRoute
  ControlsIndexRoute: typeof ControlsIndexRoute
  FrameworksIndexRoute: typeof FrameworksIndexRoute
  GapsIndexRoute: typeof GapsIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  RisksIndexRoute: typeof RisksIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  ApiIntegrationsGoogleWorkspaceConnectUrlRoute: typeof ApiIntegrationsGoogleWorkspaceConnectUrlRoute
  ApiIntegrationsGoogleWorkspaceDisconnectRoute: typeof ApiIntegrationsGoogleWorkspaceDisconnectRoute
  ApiIntegrationsGoogleWorkspaceFindingsRoute: typeof ApiIntegrationsGoogleWorkspaceFindingsRoute
  ApiIntegrationsGoogleWorkspaceGroupsRoute: typeof ApiIntegrationsGoogleWorkspaceGroupsRoute
  ApiIntegrationsGoogleWorkspaceStatusRoute: typeof ApiIntegrationsGoogleWorkspaceStatusRoute
  ApiIntegrationsGoogleWorkspaceSyncRoute: typeof ApiIntegrationsGoogleWorkspaceSyncRoute
  ApiIntegrationsGoogleWorkspaceUsersRoute: typeof ApiIntegrationsGoogleWorkspaceUsersRoute
  ApiIntegrationsGoogleWorkspaceOauthCallbackRoute: typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-website': {
      id: '/preview-website'
      path: '/preview-website'
      fullPath: '/preview-website'
      preLoaderRoute: typeof PreviewWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-ready': {
      id: '/demo-ready'
      path: '/demo-ready'
      fullPath: '/demo-ready'
      preLoaderRoute: typeof DemoReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks/': {
      id: '/risks/'
      path: '/risks'
      fullPath: '/risks/'
      preLoaderRoute: typeof RisksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps/': {
      id: '/gaps/'
      path: '/gaps'
      fullPath: '/gaps/'
      preLoaderRoute: typeof GapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/': {
      id: '/frameworks/'
      path: '/frameworks'
      fullPath: '/frameworks/'
      preLoaderRoute: typeof FrameworksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/': {
      id: '/controls/'
      path: '/controls'
      fullPath: '/controls/'
      preLoaderRoute: typeof ControlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/reviews': {
      id: '/vendors/reviews'
      path: '/vendors/reviews'
      fullPath: '/vendors/reviews'
      preLoaderRoute: typeof VendorsReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/discovery': {
      id: '/vendors/discovery'
      path: '/vendors/discovery'
      fullPath: '/vendors/discovery'
      preLoaderRoute: typeof VendorsDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/all': {
      id: '/vendors/all'
      path: '/vendors/all'
      fullPath: '/vendors/all'
      preLoaderRoute: typeof VendorsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks/$id': {
      id: '/risks/$id'
      path: '/risks/$id'
      fullPath: '/risks/$id'
      preLoaderRoute: typeof RisksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/google-workspace': {
      id: '/integrations/google-workspace'
      path: '/integrations/google-workspace'
      fullPath: '/integrations/google-workspace'
      preLoaderRoute: typeof IntegrationsGoogleWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$id': {
      id: '/integrations/$id'
      path: '/integrations/$id'
      fullPath: '/integrations/$id'
      preLoaderRoute: typeof IntegrationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps/$id': {
      id: '/gaps/$id'
      path: '/gaps/$id'
      fullPath: '/gaps/$id'
      preLoaderRoute: typeof GapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/$id': {
      id: '/frameworks/$id'
      path: '/frameworks/$id'
      fullPath: '/frameworks/$id'
      preLoaderRoute: typeof FrameworksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/$id': {
      id: '/controls/$id'
      path: '/controls/$id'
      fullPath: '/controls/$id'
      preLoaderRoute: typeof ControlsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/iso-27001': {
      id: '/assessments/iso-27001'
      path: '/assessments/iso-27001'
      fullPath: '/assessments/iso-27001'
      preLoaderRoute: typeof AssessmentsIso27001RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/iso-27001/$domainId': {
      id: '/assessments/iso-27001/$domainId'
      path: '/$domainId'
      fullPath: '/assessments/iso-27001/$domainId'
      preLoaderRoute: typeof AssessmentsIso27001DomainIdRouteImport
      parentRoute: typeof AssessmentsIso27001Route
    }
    '/api/integrations/google-workspace/users': {
      id: '/api/integrations/google-workspace/users'
      path: '/api/integrations/google-workspace/users'
      fullPath: '/api/integrations/google-workspace/users'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/sync': {
      id: '/api/integrations/google-workspace/sync'
      path: '/api/integrations/google-workspace/sync'
      fullPath: '/api/integrations/google-workspace/sync'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/status': {
      id: '/api/integrations/google-workspace/status'
      path: '/api/integrations/google-workspace/status'
      fullPath: '/api/integrations/google-workspace/status'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/groups': {
      id: '/api/integrations/google-workspace/groups'
      path: '/api/integrations/google-workspace/groups'
      fullPath: '/api/integrations/google-workspace/groups'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/findings': {
      id: '/api/integrations/google-workspace/findings'
      path: '/api/integrations/google-workspace/findings'
      fullPath: '/api/integrations/google-workspace/findings'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceFindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/disconnect': {
      id: '/api/integrations/google-workspace/disconnect'
      path: '/api/integrations/google-workspace/disconnect'
      fullPath: '/api/integrations/google-workspace/disconnect'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/connect-url': {
      id: '/api/integrations/google-workspace/connect-url'
      path: '/api/integrations/google-workspace/connect-url'
      fullPath: '/api/integrations/google-workspace/connect-url'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceConnectUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-workspace/oauth/callback': {
      id: '/api/integrations/google-workspace/oauth/callback'
      path: '/api/integrations/google-workspace/oauth/callback'
      fullPath: '/api/integrations/google-workspace/oauth/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleWorkspaceOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssessmentsIso27001RouteChildren {
  AssessmentsIso27001DomainIdRoute: typeof AssessmentsIso27001DomainIdRoute
}

const AssessmentsIso27001RouteChildren: AssessmentsIso27001RouteChildren = {
  AssessmentsIso27001DomainIdRoute: AssessmentsIso27001DomainIdRoute,
}

const AssessmentsIso27001RouteWithChildren =
  AssessmentsIso27001Route._addFileChildren(AssessmentsIso27001RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoReadyRoute: DemoReadyRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OverviewRoute: OverviewRoute,
  PoliciesRoute: PoliciesRoute,
  PreviewWebsiteRoute: PreviewWebsiteRoute,
  RequestDemoRoute: RequestDemoRoute,
  SettingsRoute: SettingsRoute,
  TestsRoute: TestsRoute,
  AssessmentsIso27001Route: AssessmentsIso27001RouteWithChildren,
  ControlsIdRoute: ControlsIdRoute,
  FrameworksIdRoute: FrameworksIdRoute,
  GapsIdRoute: GapsIdRoute,
  IntegrationsIdRoute: IntegrationsIdRoute,
  IntegrationsGoogleWorkspaceRoute: IntegrationsGoogleWorkspaceRoute,
  ReportsIdRoute: ReportsIdRoute,
  RisksIdRoute: RisksIdRoute,
  TasksIdRoute: TasksIdRoute,
  VendorsIdRoute: VendorsIdRoute,
  VendorsAllRoute: VendorsAllRoute,
  VendorsDiscoveryRoute: VendorsDiscoveryRoute,
  VendorsReviewsRoute: VendorsReviewsRoute,
  ControlsIndexRoute: ControlsIndexRoute,
  FrameworksIndexRoute: FrameworksIndexRoute,
  GapsIndexRoute: GapsIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  RisksIndexRoute: RisksIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  ApiIntegrationsGoogleWorkspaceConnectUrlRoute:
    ApiIntegrationsGoogleWorkspaceConnectUrlRoute,
  ApiIntegrationsGoogleWorkspaceDisconnectRoute:
    ApiIntegrationsGoogleWorkspaceDisconnectRoute,
  ApiIntegrationsGoogleWorkspaceFindingsRoute:
    ApiIntegrationsGoogleWorkspaceFindingsRoute,
  ApiIntegrationsGoogleWorkspaceGroupsRoute:
    ApiIntegrationsGoogleWorkspaceGroupsRoute,
  ApiIntegrationsGoogleWorkspaceStatusRoute:
    ApiIntegrationsGoogleWorkspaceStatusRoute,
  ApiIntegrationsGoogleWorkspaceSyncRoute:
    ApiIntegrationsGoogleWorkspaceSyncRoute,
  ApiIntegrationsGoogleWorkspaceUsersRoute:
    ApiIntegrationsGoogleWorkspaceUsersRoute,
  ApiIntegrationsGoogleWorkspaceOauthCallbackRoute:
    ApiIntegrationsGoogleWorkspaceOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
